//===- exi/Encode/D/EventMappings.mac -------------------------------===//
//
// Copyright (C) 2025 Eightfold
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
//     limitations under the License.
//
//===----------------------------------------------------------------===//

/// Pass in a macro that maps `From -> To`, eg. `FN(SE, StartElemEvent)`.
/// Does NOT include the `Halt` or `Invalid` cases.
#define EXI_ENCODE_EVENT_MAPPINGS(X)                                          \
  X(SE, StartElemEvent)                                                       \
  X(EE, EndElemEvent)                                                         \
  X(AT, AttrEvent)                                                            \
  X(CH, CharEvent)                                                            \
  X(NS, NamespaceEvent)                                                       \
  X(SD, StartDocEvent)                                                        \
  X(ED, EndDocEvent)                                                          \
  X(CM, CommentEvent)                                                         \
  X(PI, ProcInstrEvent)                                                       \
  X(DT, DoctypeEvent)                                                         \
  X(ER, EntityRefEvent)                                                       \
  X(SC, SelfContEvent)
