//===- exi/Basic/D/LogPosition.mac ----------------------------------===//
//
// Copyright (C) 2025-2026 Ninefold
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
//     limitations under the License.
//
//===----------------------------------------------------------------===//

// TODO: Move EXI_LOG_POSITION
#define EXI_LOG_POSITION 1

#undef LOG_POSITION
#if EXI_LOG_POSITION
/// Logs the current position using `bitPos`
/// FIXME: Update LOG_POSITION to take any Ref?
# define LOG_POSITION(...) do {                                               \
  if (hasDbgLogLevel(VERBOSE)) {                                              \
    const auto BitPos = (__VA_ARGS__)->bitPos();                              \
    logColoredInDbgWithPositionAndType(BitPos, __func__, __LINE__);           \
  }                                                                           \
} while(0)
#else
# define LOG_POSITION(...) ((void)0)
#endif
