//===- exi/Decode/D/Decode.mac --------------------------------------===//
//
// Copyright (C) 2025 Ninefold
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
//     limitations under the License.
//
//===----------------------------------------------------------------===//

#undef EXI_INSTANTIATE_DECODER_FUNCS
/// Templated functions for ExiDecoder.
/// TODO: Add version for smaller binary.
#define EXI_INSTANTIATE_DECODER_FUNCS(X)  \
  X(OrderedReader)                        \
  X(BitReader)                            \
  X(ByteReader)

/// Templated functions for ExiDecoder.
#define EXI_DECODER_FUNCS_IMPL(KW, TYPE)                                              \
KW template ExiResult<EventUID> ExiDecoder::decodeQName<TYPE>();                      \
KW template ExiResult<EventUID> ExiDecoder::decodeNS<TYPE>();                         \
KW template ExiResult<CompactID> ExiDecoder::decodeURI<TYPE>();                       \
KW template ExiResult<CompactID> ExiDecoder::decodeName<TYPE>(CompactID URI);         \
KW template ExiResult<Option<CompactID>> ExiDecoder::decodePfxQ<TYPE>(CompactID URI); \
KW template ExiResult<CompactID> ExiDecoder::decodePfx<TYPE>(CompactID URI);          \
KW template ExiResult<EventUID> ExiDecoder::decodeValue<TYPE>(SmallQName Name);
